# Generated by Django 3.2.3 on 2021-06-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_coefficient', models.IntegerField()),
                ('b_coefficient', models.IntegerField()),
            ],
        ),
    ]
