# Generated by Django 3.2.3 on 2021-06-11 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=150)),
                ('license_plate', models.CharField(max_length=150)),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('amount_paid', models.IntegerField(blank=True, default=None, null=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='levels.levelspace')),
            ],
        ),
    ]
